FROM python:3.6-alpine

RUN apk update
RUN apk add musl-dev wget git build-base libxslt-dev

RUN pip install cython 
RUN ln -s /usr/include/locale.h /usr/include/xlocale.h
RUN pip install numpy
RUN wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz && \
  tar -xvzf ta-lib-0.4.0-src.tar.gz && \
  cd ta-lib/ && \ 
  ./configure --prefix=/usr && \
  make && \
  make install
RUN git clone https://github.com/mrjbq7/ta-lib.git /ta-lib-py && cd ta-lib-py && python setup.py install
RUN pip install requests
RUN pip install lxml
RUN pip install pandas
RUN pip install 'elasticsearch>=7.0.0,<8.0.0' 